Handle empty ViewPager
laenger/ViewPagerBottomSheet pull request #24
Opened 2018-05-04 15:20 UTC by crehmann

I am using a ViewPager with an adapter. When the adapter was empty, the ViewPagerBottomSheetBehavior caused a NullPointerException.

2018-05-04 22:06 UTC, laenger requested changes
thank you for your PR, just a minor comment

2018-05-04 22:06 UTC, laenger commented on vpbs/src/main/java/biz/laenger/android/vpbs/ViewPagerBottomSheetBehavior.java
> +            if(currentViewPagerChild == null){
formatting is off

2018-05-16 11:33 UTC, crehmann commented
I have updated the PR.

2018-06-07 14:26 UTC, merged

2019-06-13 11:23 UTC, vimalpsojan commented
I am using your library. Still getting #23 issue with latest version 0.0.5.  Can you please release new version.

2019-06-13 11:31 UTC, vimalpsojan commented
I am using your library, Can you please release new version with this fix.

2019-07-24 15:30 UTC, rnjssh96 commented
I think this fix has been removed in the latest release. Please include the same solution again.

2019-07-25 08:10 UTC, rnjssh96 commented
I think this is not uploaded to the maven repository